name: Demo Pipeline

on: 
    push:
        branches:
            - main
            - dev
    pull_request:
        branches: [main, dev]
    # schedule:
    #     - cron: "*/1 * * * *"

jobs:

    setup_job:
        runs-on: ubuntu-latest # macOS-latest, windows-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Create a file
              run: |
                touch github_action.txt
                echo from first job > github_action.txt
                ls -la
                echo Hello World
                cat README.md
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                 name: my file
                 path: github_action.txt

    build_job:
        needs: 
            - setup_job
        runs-on: ubuntu-latest
        steps:
            - name: display hello
              run: echo hello
            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                name: my file
            - name: Display github_action.txt 
              run: cat github_action.txt
    deploy_job:
        needs: build_job
        runs-on: macOS-latest
        steps:
            - run: echo hello mac
